### ISSUE TITLE
inhalte werden nicht gerendert

### ISSUE THREAD

**Issue by gisma** [IvoJJ/aGis-2021-2022#1]
@IvoJJ  Falls es noch Problme bei rendern der inhalte gibt bitte aus dem yaml frontmatter  die folgenden items löschen:
```yaml
output:
  blogdown::html_page:
    keep_md: yes
```
evtl. auch den `source` Befehl wie folgt erweitertn
`source(file.path(envimaR::alternativeEnvi(root_folder = root_folder),"src/000-rspatial-setup.R"),local = knitr::knit_global())`

btw i like the title images...
